export default {
  RESIZER_SECRET_KEY: '%{AQICAHiH7W8m/ZwSizPtJ5+e3MKEKRvPhAGdG3pC/jWLxGpnzgEx7b893/kSldl70xSYlj1SAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMyxMUVNeEzjNyzc0mAgEQgDvFEJDjgCH1DkBHtgunICQMa5w+sbayFV01ZH09BGNqvAbmReY2L29S3LChDHfC4nKfzTXCIqedZ/URDA==}',
  CHARTBEAT_KEY: '%{AQICAHiH7W8m/ZwSizPtJ5+e3MKEKRvPhAGdG3pC/jWLxGpnzgHGgnG7SWrTSPbNmokI5EV/AAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMj5kkSufxJyxG8E9NAgEQgDskkHuKt9hg6lJKX8MPNOo2Tdjo/B2sWYd3l7F6TwjT4C30zN4jm+eKFZLdoCUebRQQz4/FIvIp1S/lBA==}',
  SOPHI_CLIENT_ID: '%{AQICAHiH7W8m/ZwSizPtJ5+e3MKEKRvPhAGdG3pC/jWLxGpnzgEG3y1mXjN6Rvjclfd7vrYrAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMlSoxe/OWunSeDj3RAgEQgDuuA6qZ+Ob95EbnRB3oPea8aHT1kH05twz/NmRjAE6VL80j12VnaJt8kPotIlZMkm7BmndHp3TkJU3kQQ==}',
  SOPHI_CLIENT_SECRET: '%{AQICAHiH7W8m/ZwSizPtJ5+e3MKEKRvPhAGdG3pC/jWLxGpnzgHY9HApw679A+g+eHdnQGiUAAAAojCBnwYJKoZIhvcNAQcGoIGRMIGOAgEAMIGIBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDPoog/ax6Kg8CyIprgIBEIBbKVQSQYIK+Oo3xWoHA2krNhsNOkgo3s5wZrKLiIxdzr9x5fsccxOxdmEz7wfy65z/SbJ+vx6aBsG6n5vzV7NDRvufEB8xThoCiCg42gLd+ZLn9YXwwY5ckBY/2w==}',
  SOPHI_ENDPOINT: 'https://site-automation-api.ml.sophi.io/curatedHosts/www.ajc.com/curator',
  SOPHI_TOKEN_URL: 'https://sophi-prod.auth0.com/oauth/token',
  SOPHI_TOKEN_AUDIENCE: 'https://api.sophi.io',
};
