import React from 'react';

const AmpScripts = () => (
  <>
    <script
      async
      src="https://cdn.ampproject.org/v0.js"
    />
    <script
      async
      custom-element="amp-position-observer"
      src="https://cdn.ampproject.org/v0/amp-position-observer-0.1.js"
    />
    <script
      async
      custom-element="amp-animation"
      src="https://cdn.ampproject.org/v0/amp-animation-0.1.js"
    />
    <script
      async
      custom-element="amp-sidebar"
      src="https://cdn.ampproject.org/v0/amp-sidebar-0.1.js"
    />
    <script
      async
      custom-element="amp-fx-flying-carpet"
      src="https://cdn.ampproject.org/v0/amp-fx-flying-carpet-0.1.js"
    />
    <script
      async
      custom-element="amp-social-share"
      src="https://cdn.ampproject.org/v0/amp-social-share-0.1.js"
    />
    <script
      async
      custom-element="amp-ad"
      src="https://cdn.ampproject.org/v0/amp-ad-0.1.js"
    />
    <script
      async
      custom-element="amp-video"
      src="https://cdn.ampproject.org/v0/amp-video-0.1.js"
    />
    <script
      async
      custom-element="amp-youtube"
      src="https://cdn.ampproject.org/v0/amp-youtube-0.1.js"
    />
    <script
      async
      custom-element="amp-iframe"
      src="https://cdn.ampproject.org/v0/amp-iframe-0.1.js"
    />
    <script
      async
      custom-element="amp-twitter"
      src="https://cdn.ampproject.org/v0/amp-twitter-0.1.js"
    />
    <script
      async
      custom-element="amp-instagram"
      src="https://cdn.ampproject.org/v0/amp-instagram-0.1.js"
    />
    <script
      async
      custom-element="amp-facebook"
      src="https://cdn.ampproject.org/v0/amp-facebook-0.1.js"
    />
    <script
      async
      custom-element="amp-vimeo"
      src="https://cdn.ampproject.org/v0/amp-vimeo-0.1.js"
    />
    <script
      async
      custom-element="amp-reddit"
      src="https://cdn.ampproject.org/v0/amp-reddit-0.1.js"
    />
    <script
      async
      custom-element="amp-soundcloud"
      src="https://cdn.ampproject.org/v0/amp-soundcloud-0.1.js"
    />
    <script
      async
      custom-element="amp-carousel"
      src="https://cdn.ampproject.org/v0/amp-carousel-0.2.js"
    />
    <script
      async
      custom-element="amp-pinterest"
      src="https://cdn.ampproject.org/v0/amp-pinterest-0.1.js"
    />
  </>
);

export default AmpScripts;
