export default {
  dfp_id: 21849707860,
  siteName: 'dayton',
  cdnOrg: 'coxohio',
  cdnSite: 'dayton',
  siteDomainURL: 'https://sandbox.dayton.arcpublising.com/pf',
  websiteURL: 'https://www.dayton.com/',
  websiteLogo: 'https://cloudfront-us-east-1.images.arcpublishing.com/sandbox.ajc/CFSFLNZIUJBB3EVHSGSJCOHOJM.png',
  googleLogo: 'https://cloudfront-us-east-1.images.arcpublishing.com/coxohio/YRHUB5MLSRHN3GFTFUEH36LH4M.png',
  orgName: 'Dayton',
  domainTwitterURL: 'https://www.twitter.com/daytondotcom/',
  twitterURL: 'https://twitter.com/intent/tweet?url=',
  domainFacebookURL: 'https://www.facebook.com/daytondotcom/',
  facebookURL: 'https://www.facebook.com/share.php?u=',
  domainPinterestURL: 'https://www.pinterest.com/daytondotcom/',
  pinterestURL: 'https://www.pinterest.com/pin/create/button/?url=',
  domainRedditURL: 'https://www.reddit.com/domain/dayton.com/',
  redditURL: 'https://www.reddit.com/submit?url=',
  footerLogo: '/resources/logos/Dayton/logo-full.svg',
  logo: '/resources/logos/Dayton/logo-full.svg',
  logoShort: '/resources/logos/Dayton/logo-short.svg',
  logoHamburger: '/resources/logos/Dayton/logo-mobile-hamburger.svg',
  mail: 'mailto:?Subject=',
  sites: ['dayton'],
  weatherLocationId: 330120,
  taboola: {
    dataPublisher: 'cox-dayton',
  },
  favicon: '/resources/icons/favicons/Ohio/dayton-favicon.ico',
};
