import adsTxt from './adstxt/dayton.com.json';
import appAdsTxt from './appadstxt/dayton.com.json';

export default {
  dfp_id: 21849707860,
  siteName: 'dayton',
  cdnOrg: 'coxohio',
  cdnSite: 'dayton',
  siteDomainURL: 'https://www.dayton.com',
  websiteURL: 'https://www.dayton.com/',
  websiteLogo: 'https://cloudfront-us-east-1.images.arcpublishing.com/coxohio/YRHUB5MLSRHN3GFTFUEH36LH4M.png',
  googleLogo: 'https://cloudfront-us-east-1.images.arcpublishing.com/coxohio/YRHUB5MLSRHN3GFTFUEH36LH4M.png',
  orgName: 'Dayton',
  domainTwitterURL: 'https://www.twitter.com/daytondotcom/',
  twitterURL: 'https://twitter.com/intent/tweet?url=',
  domainFacebookURL: 'https://www.facebook.com/daytondotcom/',
  facebookURL: 'https://www.facebook.com/share.php?u=',
  domainPinterestURL: 'https://www.pinterest.com/daytondotcom/',
  pinterestURL: 'https://www.pinterest.com/pin/create/button/?url=',
  pinterestShareLogo: 'https://cloudfront-us-east-1.images.arcpublishing.com/sandbox.coxohio/2L4CESVBVRBE7M2XATT7PR3IZ4.png',
  domainRedditURL: 'https://www.reddit.com/domain/dayton.com/',
  redditURL: 'https://www.reddit.com/submit?url=',
  footerLogo: '/resources/logos/Dayton/logo-full.svg',
  logo: '/resources/logos/Dayton/logo-full.svg',
  logoShort: '/resources/logos/Dayton/logo-short.svg',
  logoHamburger: '/resources/logos/Dayton/logo-mobile-hamburger.svg',
  logoPlaceholder: '/resources/logos/Dayton/placeholder.svg',
  logoOgImage: '/resources/logos/Dayton/logo-ogimage.png',
  mail: 'mailto:?Subject=',
  sites: ['dayton'],
  featuredVideoPlayerRules: {
    startPlaying: true,
    muteON: true,
    autoplayNext: true,
  },
  inlineVideoPlayerRules: {
    startPlaying: false,
    muteON: true,
    autoplayNext: true,
  },
  weatherLocationId: 330120,
  taboola: {
    dataPublisher: 'cox-dayton',
  },
  metrics: {
    siteID: 'daytondotcom',
    siteMetro: 'oh: dayton',
    siteFormat: 'entertainment',
    gtmContainerKey: 'GTM-W3VLHBK',
    ampGtmID: 'GTM-T46L3LB',
  },
  adsPath: 'dayton_np/daytoncom_web_default',
  favicon: '/resources/icons/favicons/Ohio/dayton-favicon.ico',
  adsTxt,
  appAdsTxt,
};
