export default {
  dfp_id: 21849707860,
  siteName: 'dayton',
  siteDomainURL: 'https://sandbox.dayton.arcpublising.com/pf',
  websiteURL: 'https://www.dayton.com/',
  websiteLogo: 'https://cloudfront-us-east-1.images.arcpublishing.com/sandbox.ajc/CFSFLNZIUJBB3EVHSGSJCOHOJM.png',
  googleLogo: 'https://cloudfront-us-east-1.images.arcpublishing.com/sandbox.ajc/TXGQ6XIXWNACDAKSABXGTXAKU4.png',
  orgName: 'The Atlanta Journal-Constitution',
  domainTwitterURL: 'https://twitter.com/daytondailynews',
  twitterURL: 'https://twitter.com/intent/tweet?url=',
  domainFacebookURL: 'https://www.facebook.com/daytondotcom/',
  facebookURL: 'https://www.facebook.com/share.php?u=',
  domainPinterestURL: 'https://www.pinterest.com/daytondotcom/',
  pinterestURL: 'https://www.pinterest.com/pin/create/button/?url=',
  domainRedditURL: 'https://www.reddit.com/domain/dayton.com/',
  redditURL: 'https://www.reddit.com/submit?url=',
  logo: '/resources/images/dayton-logo.svg',
  mail: 'mailto:?Subject=',
  sites: ['dayton'],
  maxTabletViewWidth: 1024,
  weatherLocationId: 330120,
};
