import adsTxt from './adstxt/journal-news.com.json';
import appAdsTxt from './appadstxt/journal-news.com.json';

export default {
  dfp_id: 21849707860,
  siteName: 'journal-news',
  cdnOrg: 'coxohio',
  cdnSite: 'journal-news',
  siteDomainURL: 'https://sandbox.journal-news.arcpublishing.com/pf',
  websiteURL: 'https://www.journal-news.com/',
  websiteLogo: 'https://cloudfront-us-east-1.images.arcpublishing.com/coxohio/DK42MHKQZRA7PFSGW7YUX4A4DQ.png',
  googleLogo: 'https://cloudfront-us-east-1.images.arcpublishing.com/coxohio/DK42MHKQZRA7PFSGW7YUX4A4DQ.png',
  orgName: 'Journal News',
  domainTwitterURL: 'https://twitter.com/journalnews',
  twitterURL: 'https://twitter.com/intent/tweet?url=',
  domainFacebookURL: 'https://www.facebook.com/journalnews',
  facebookURL: 'https://www.facebook.com/share.php?u=',
  domainPinterestURL: '',
  pinterestURL: 'https://www.pinterest.com/pin/create/button/?url=',
  pinterestShareLogo: 'https://cloudfront-us-east-1.images.arcpublishing.com/sandbox.coxohio/NDGCHKDQUNDTLL5XSWQJMKNZIA.png',
  domainRedditURL: '',
  redditURL: 'https://www.reddit.com/submit?url=',
  footerLogo: '/resources/logos/JournalNews/logo-full.svg',
  logo: '/resources/logos/JournalNews/logo-full.svg',
  logoShort: '/resources/logos/JournalNews/logo-short.svg',
  logoHamburger: '/resources/logos/JournalNews/logo-mobile-hamburger.svg',
  logoPlaceholder: '/resources/logos/JournalNews/placeholder.svg',
  logoOgImage: '/resources/logos/JournalNews/logo-ogimage.png',
  mail: 'mailto:?Subject=',
  sites: ['journal-news'],
  breakingNewsID: 'FIQH7IEKK5H5LHRAII5AY7VDCU',
  breakingLiveVideoID: '52EEYZZB6BDYZDOFFNPJBO2ZJA',
  breakingNewsID_sandbox: 'BYPUKOTQLRAMLDYR5C3XLJOVZQ',
  breakingLiveVideoID_sandbox: 'A4KCYNGXMBGHRF6JABDFEHFFCE',
  featuredVideoPlayerRules: {
    startPlaying: true,
    muteON: true,
    autoplayNext: true,
  },
  inlineVideoPlayerRules: {
    startPlaying: false,
    muteON: true,
    autoplayNext: true,
  },
  weatherLocationId: 330109,
  taboola: {
    dataPublisher: 'cox-journal-news',
    taboolaStoryID: 'taboola-journal-news-custom-feed',
    taboolaSectionID: 'taboola-journal-news-custom-feed---section-fronts',
    cdnLink: '//cdn.taboola.com/libtrc/cox-journal-news/loader.js',
    containerName: 'taboola-journal-news-custom-feed',
    placementName: 'Journal News Custom Feed',
  },
  metrics: {
    siteID: 'journal-news',
    siteMetro: 'oh: dayton',
    siteFormat: 'news',
    gtmContainerKey: 'GTM-NNFL6V6',
    ampGtmID: 'GTM-WQBXD72',
  },
  adsPath: 'dayton_np/jnws_web_default',
  favicon: '/resources/icons/favicons/Ohio/journal-news-favicon.ico',
  adsTxt,
  appAdsTxt,
};
