export default {
  dfp_id: 21849707860,
  siteName: 'journal-news',
  siteDomainURL: 'https://sandbox.journal-news.arcpublishing.com/pf',
  websiteURL: 'https://www.journal-news.com/',
  websiteLogo: 'https://cloudfront-us-east-1.images.arcpublishing.com/sandbox.ajc/CFSFLNZIUJBB3EVHSGSJCOHOJM.png',
  googleLogo: 'https://cloudfront-us-east-1.images.arcpublishing.com/sandbox.ajc/TXGQ6XIXWNACDAKSABXGTXAKU4.png',
  orgName: 'The Atlanta Journal-Constitution',
  domainTwitterURL: 'https://twitter.com/journalnews',
  twitterURL: 'https://twitter.com/intent/tweet?url=',
  domainFacebookURL: 'https://www.facebook.com/journalnews',
  facebookURL: 'https://www.facebook.com/share.php?u=',
  domainPinterestURL: '',
  pinterestURL: 'https://www.pinterest.com/pin/create/button/?url=',
  domainRedditURL: '',
  redditURL: 'https://www.reddit.com/submit?url=',
  logo: '/resources/images/springfieldnewssun-logo.svg',
  mail: 'mailto:?Subject=',
  sites: ['journal-news'],
  featuredVideoPlayerRules: {
    startPlaying: true,
    muteON: true,
    autoplayNext: true,
  },
  inlineVideoPlayerRules: {
    startPlaying: false,
    muteON: true,
    autoplayNext: true,
  },
  maxTabletViewWidth: 1024,
};
